### ISSUE TITLE
missing revelation type

### ISSUE THREAD

**Issue by egcp** [bkloppenborg/revelation-to-keepassxc#1] opened 2020-07-08 20:40 UTC
Thanks for creating the revelation-to-keepassxc converter. It seems that you created all different types of Revelation entries, except for Website. Since most of my passwords are under the "Website" type in Revelation they do not get exported to the CSV file, even though they are exported from revelation correctly in the XML file. Your first screenshot is missing that type too. Is there an easy way to add it?

**Comment by bkloppenborg** [comment] 2020-07-08 23:47
Hunh. I really don't know how I missed that one! Thanks for catching it. The issue is resolved in ecbd4c4, which is now the current master branch.

**Closed as completed by bkloppenborg** 2020-07-08 23:47 UTC
